# Makefile pour installer automatiquement les scripts utilisés dans les règles udev

install:
	sudo cp -r ./script-udev/ /usr/local/bin/
	sudo mkdir -p /usr/local/etc/log
	sudo cp ./rules-udev/* /etc/udev/rules.d/
